openapi: 3.0.3
info:
  title: Patient Eligibility Signposting API
  version: 1.0.13-alpha
  description: "## Overview\nUse this API to access the [Patient Eligibility Signposting Data Product](https://digital.nhs.uk/services/eligibility-data-product-elid) - the nationally curated single source of eligibility status and signposted actions for individuals.  For example, you can request eligibility for one or more vaccination types to understand if NHS England holds information which suggest that the person could or should take further steps toward receiving those vaccinations, and optionally, a list of the steps NHS England would recommend.\nWhere someone is deemed eligible, they will also be classified as actionable or not actionable. When deemed not actionable, one or more reasons will be returned.  These reasons can range from personal care setting impacts to current lack of availability of vaccines and more.\nThe API returns most of its data in both code and text form.  Unless agreed in writing with NHS England, where text is provided it should be displayed to the user as-is.\nUse this API to request: \n* eligibility for all supported categories and conditions\n* eligibility for specified supported categories and/or conditions \n* request that actions be included in the response\n* request that actions not be included in the response\nYou cannot currently use this API to: \n* request eligibility for proxy people (familial relations etc.)\n* request actions for people considered ineligible\nThis API is read-only and can return a list of processed suggestions, each relating to a 'condition' (e.g. COVID, RSV, BOWEL, EYE, BREAST etc.), including the following information for each: \n* a code representing the condition (COVID, RSV, BOWEL, EYE, BREAST)\n* an overall status (NotEligible, NotActionable, Actionable) \n* a list of eligibility cohort groups to which the person belongs (when eligible)\n* a list of the cohort groups that could have made the person eligible (when not eligible) \n* a list of rules/reasons that deem a person to be NotActionable\n* a list of actions that should be shown to the consumer\n#### Definitions of overall status\nThe overall status values indicate the following:\n* NotEligible - the individual does not currently meet eligibility criteria\n* NotActionable - the individual is eligible but does not need to take any further action at this time \n* Actionable - the individual is eligible and should follow one of the recommended actions provided\n### Patients included in the Patient Eligibility Signposting API\nThe API will return data for all patients who are in the NHS PDS system that are registered with an English GP practice (or one administered by England) or who we believe to be resident in England.\nPatients who are deceased (or thought to be), marked as invalid or sensitive will not be processed by this API.\n## Who can use this API\nThis API can only be used where there is a [legal basis](https://digital.nhs.uk/services/eligibility-data-product-elid#who-this-service-is-for) to do so. Make sure you have a valid use case before you go too far with your development.  You must demonstrate you have a [valid use case](https://digital.nhs.uk/services/eligibility-data-product-elid#who-this-service-is-for) as part of digital onboarding.\nYou must do this before you can go live (see 'Onboarding' below).\n### Who can access Eligibility Signposting Information\nPatients who receive health and social care or make use of NHS services in England, Wales and the Isle of Man can access their own Eligibility Signposting data through onboarded services.\nHealth and care organisations in England and the Isle of Man can access our information for legitimate direct care purposes. Legitimate direct care examples include NHS organisations delivering healthcare, local authorities delivering care, third sector and private sector health and care organisations, and developers delivering systems to health and care organisations.\n### Existing API users\nTo find out which healthcare software development organisations and products are already using this API, see [Patient Eligibility Signposting API - integrated products](https://digital.nhs.uk/services/eligibility-data-product-elid).\n## Access modes This API currently has only one access mode:\n* patient access (user-restricted)\nWe are considering the possibility of adding other modes in the future: \n* healthcare worker access\n* application restricted access\n### Patient access\nIf the end user is a patient then you must use this access mode. Use this access mode to obtain data for that patient.\nThis access mode is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present, authenticated and authorised.\nThe end user must be:\n* a patient who receives health and social care or makes use of NHS services \n* strongly authenticated, using [NHS login](https://digital.nhs.uk/services/nhs-login)\nTo use this access mode, you must currently use the following security pattern:\n|\tSecurity pattern\t\t                                                                                                                                                                                                          |\tTechnical details\t                                  |\tAdvantages\t                                                | Disadvantages                                           |\n|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| ----------------------------------------------------| ------------------------------------------------------------|---------------------------------------------------------| |[NHS login - separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation) |OAuth 2.0 token exchange with signed JWT             |Gives access to user information.                            |Need to integrate and onboard separately with NHS login. |\nPatient access mode users must be authenticated to a high proofing level (P9) and to one of the following [vectors of trust](https://nhsconnect.github.io/nhslogin/vectors-of-trust/):\n* P9.Cp.Cd \n* P9.Cp.Ck\n* P9.Cm\nThis access mode is available in production ([beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status)).\n### Restricted access This access mode is not yet available, if you believe this mode would benefit your use-case, please let us know.\nThis access mode is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate and authorise the calling application but not the end user.\nThis access mode is not designed to be accessed by an end user. You might use this access mode as part of a back-end process to:\n* retrieve eligibility signposting information into a system in advance of a clinic \n* retrieve eligibility signposting information into a system to be used in a disconnected manner\nTo use this access mode, use this security pattern:\n* [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)\n## Roadmap\nThe [Patient Eligibility Signposting API](https://digital.nhs.uk/services/eligibility-data-product-elid/eligibility-data-product-elid-roadmap) roadmap shows the planned changes for the API.\nTo see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/612352/eligibility-signposting-api-vaccinations).\nIf you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).\n## Service level\nThis API is a silver service, meaning it is operational 24 hours a day, 365 days a year and supported 8am to 6pm, Monday to Friday excluding bank holidays.\nFor more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).\n## Rate limits\nThe default rate limit is 25TPS (Transactions Per Second), per app. If you require a higher rate limit please [contact us](https://digital.nhs.uk/developer/help-and-support). or raise this during the onboarding process.\n## Technology\nThis API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).\nThe error messages returned by this API conform to the FHIR global standard for health care data exchange, specifically to FHIR R4 (v4.0.1). This is to aid consumers that integrate to FHIR based APIS and are in any case not overly complex.\nThere are [libraries and SDKs](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) available to help with FHIR API integration.\n## Network access\nThis API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).\nFor more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).\n## Errors\nWe use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:\n* 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action \n* 400 to 499 if it failed because of a client error by your application\n* 500 to 599 if it failed because of an error on our server\nErrors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.\nYour API-calling application should have a mechanism to automatically try again, for example by giving status information to your end user, before giving up. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#error-handling) for more information about error handling.\n## Open source\nYou might find the following [open source](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#open-source) resources useful:\n| Resource                  | Description                                                          | Links                                                                          |\n|---------------------------|----------------------------------------------------------------------|--------------------------------------------------------------------------------| | Patient Eligibility Signposting API| Source code including API proxy, sandbox and specification and code.      | [GitHub repo](https://github.com/NHSDigital/eligibility-signposting-api) |\nWe currently don't have any open source client libraries or sample code for this API. If you think this would be useful, you can [upvote the suggestion on our Interactive Product Backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/107439/client-libraries-and-reference-implementations).\n\n## Environments and testing\n| Environment       | Base URL                                                               | | ----------------- | ---------------------------------------------------------------------- |\n| Sandbox           | `https://sandbox.api.service.nhs.uk/eligibility-signposting-api/patient-check/{id}`    | | Integration test  | `https://int.api.service.nhs.uk/eligibility-signposting-api/patient-check/{id}`        |\n| Production        | `https://api.service.nhs.uk/eligibility-signposting-api/patient-check/{id}`            |\n### Sandbox testing\nOur [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):\n* is for early developer testing \n* only covers a limited set of scenarios\n* is open access, so does not allow you to test authorisation\nFor details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.\nAlternatively, you can try out the sandbox using our Postman collection:\n[![Run in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/eligibility-signposting-api/eligibility-signposting-api)\n### Integration testing\nOur [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):\n* is for formal integration testing \n* includes authorisation, with options for user-restricted access (NHS Login)\n### Production smoke testing\nYou must not use real patient data for smoke testing in the production environment.\nRather, use our [production test patient](https://digital.nhs.uk/services/eligibility-signposting/api-test-data#production-smoke-testing).\n## Onboarding\nYou need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it is worth planning well ahead.\nAs part of this process, you need to demonstrate your technical conformance to the requirements for this API.\nYou also need to demonstrate that you can manage risks. This might impact the design of your software. For details, see [Onboarding support information](https://digital.nhs.uk/services/eligibility-data-product-elid#how-to-access-this-service).\nTo understand how our online digital onboarding process works, see [digital onboarding](https://digital.nhs.uk/developer/guides-and-documentation/digital-onboarding).\n## Related APIs\nThe following APIs are related to this API:\n"
  contact:
    url: https://developer.nhs.uk/apis/eligibility-signposting-api
  termsOfService: https://developer.nhs.uk/apis/eligibility-signposting-api
tags:
  - name: Eligibility
  - name: Signposting
  - name: NextActions
servers:
  - url: https://sandbox.api.service.nhs.uk/eligibility-signposting-api
    description: Sandbox Server
  - url: https://int.api.service.nhs.uk/eligibility-signposting-api
    description: Integration Server
  - url: https://api.service.nhs.uk/eligibility-signposting-api
    description: Production Server
paths:
  /patient-check/{id}:
    get:
      summary: Check Eligibility
      description: >-
        Determines which suggestions a person is eligible for and which they are
        not, including reasons and next steps.
      security:
        - environment-specific-secured: []
      operationId: checkEligibility
      parameters:
        - name: id
          in: path
          description: The NHS number of the person to check eligibility for. The primary identifier of a patient, unique within NHS England and Wales. Always 10 digits and must be a [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
          required: true
          schema:
            type: string
            example: '9000000009'
        - name: category
          in: query
          required: false
          schema:
            type: string
            example: VACCINATIONS
            default: ALL
            enum:
              - VACCINATIONS
              - SCREENING
              - ALL
          description: >-
            The category for which the caller is checking eligibility
            suggestions. If not provided, eligibility for all supported
            categories will be checked.
        - name: conditions
          in: query
          required: false
          schema:
            type: string
            example: FLU,RSV
            default: ALL
          description: >-
            The diseases or conditions for which the caller is checking
            eligibility suggestions in a comma separated list. If not provided, eligibility for all
            supported diseases will be checked.
        - name: includeActions
          in: query
          required: false
          schema:
            type: string
            example: Y
            default: Y
            enum:
              - Y
              - N
          description: >-
            When Y is passed in, the API response will include zero or more actions as applicable.  Passing in N will result in no actions being calculated or returned.
        - in: header
          name: X-Request-ID
          required: false
          description: |
            A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests and to trace the request if you contact our helpdesk.

            Must be a universally unique identifier (UUID) (ideally version 4).

            Mirrored back in a response header.

            If you re-send a failed request, use the same value in this header.
          schema:
            type: string
            pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
            example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
        - in: header
          name: X-Correlation-ID
          required: false
          description: |
            An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.

            Mirrored back in a response header.
          schema:
            type: string
            example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
        - in: header
          name: NHSD-End-User-Organisation-ODS
          required: false
          description: |
            The ODS code of the user.

            Mandatory for client applications which service multiple end user organisations (EUO). This will allow the calls to be attributed to the correct EUO.
          schema:
            type: string
            example: Y12345
      responses:
        '200':
          description: Eligibility response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseId:
                    type: string
                    description: GUID assigned when the decisioning evaluation is carried out.  This will be useful if you ever need to request support for a particular request.  This will not change if you receive a cached response.
                    example: 1a233ba5-e1eb-4080-a086-2962f6fc3473
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        description: Timestamp of when the decisioning evaluation is carried out.  This will not change if you receive a cached response.
                        example: '2025-02-12T16:11:22+00:00'
                  processedSuggestions:
                    type: array
                    description: List of suggestions the person is eligible for.
                    items:
                      type: object
                      properties:
                        condition:
                          type: string
                          example: RSV
                          description: String representing the vaccine target disease, screening target or other scenario requiring decision based suggestions, that this suggestion relates to
                        status:
                          type: string
                          example: Actionable
                          description: String representing an overall summary of the persons status for this processedSuggestion
                          enum:
                            - NotEligible
                            - NotActionable
                            - Actionable
                        statusText:
                          type: string
                          example: Actionable - Individual is eligible and we suggest that they follow one or more of the provided actions
                        eligibilityCohorts:
                          type: array
                          description: Cohorts that drove the eligibility status returned.
                          items:
                            type: object
                            properties:
                              cohortCode:
                                type: string
                                description: Machine readable code signifying the cohort/cohort group that lead to a person's eligibility for this suggestion
                              cohortText:
                                type: string
                                description: Human readable (render-able) text describing the meaning of a cohort/cohort group that lead to a person's eligibility for this suggestion
                              cohortStatus:
                                type: string
                                description: String representing the persons status for this processedSuggestion in respect of this particular cohort or cohort group
                                enum:
                                  - NotEligible
                                  - NotActionable
                                  - Actionable
                          example:
                              - cohortCode: 'rsv_75-79_initial'
                                cohortText: You turned 80 after 1 September 2024, so are eligible for the RSV vaccine until 31 August 2025
                                cohortStatus: NotEligible
                              - cohortCode: 'rsv_75-79_ongoing'
                                cohortText: You're aged 75 to 79
                                cohortStatus: Actionable
                        suitabilityRules:
                          type: array
                          description: Reasons that the eligibility status was changed from the base eligibility to result in it's status to not be eligible or to be acted on
                          items:
                            type: object
                            properties:
                              ruleType:
                                type: string
                                description: The type of a rule that triggered to amend the status of the suggestion
                                enum:
                                  - F
                                  - S
                              ruleCode:
                                type: string
                                description: Machine readable code signifying a rule that amended the status of the suggestion
                              ruleText:
                                type: string
                                description: Human readable (render-able) text describing a rule that amended the status of the suggestion (optionally GFM Markdown)
                        actions:
                          type: array
                          description: List of actions to be shown to the person.
                          items:
                            type: object
                            properties:
                              actionType:
                                type: string
                                description: Type of action to render.  E.g. A primary button, a link, text etc
                              actionCode:
                                type: string
                                description: Code representing the action to be taken
                              description:
                                type: string
                                description: Human readable (render-able) text describing the suggested action (optionally GFM Markdown)
                              urlLink:
                                type: string
                                description: URL to invoke if action selected.
                                example: "https://mylink.mydomain.tld"
                              urlLabel:
                                type: string
                                description: Lable to use for the URL (or button) used to display the link
                                example: "My Link Label"
              examples:
                example_50000000001:
                  summary: RSV - Actionable due to membership of an Age Cohort including suggested national booking action (actions requested)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "Actionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are aged 75 to 79 years old."
                            cohortStatus: "Actionable"
                        suitabilityRules: []
                        actions:
                          - actionType: "ButtonWithAuthLink"
                            actionCode: "BookNBS"
                            description: ""
                            urlLink: "http://www.nhs.uk/book-rsv"
                            urlLabel: "Continue to booking"
                example_50000000002:
                  summary: RSV - Actionable due to membership of an Age Cohort including suggested action (not national booking)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "Actionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are aged 75 to 79 years old."
                            cohortStatus: "Actionable"
                        suitabilityRules: []
                        actions:
                          - actionType: "InfoText"
                            actionCode: "BookLocal"
                            description: "##Getting the vaccine\nYou can get an RSV vaccination at your GP surgery.\nYour GP surgery may contact you about getting the RSV vaccine. This may be by letter, text, phone call, email or through the NHS App. You do not need to wait to be contacted before booking your vaccination."
                example_50000000003:
                  summary: RSV - Actionable due to membership of an alternative Age Cohort including suggested action (not national booking)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "Actionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_catchup"
                            cohortText: "You turned 80 between 2nd September 2024 and 31st August 2025"
                            cohortStatus: "Actionable"
                        suitabilityRules: []
                        actions:
                          - actionType: "InfoText"
                            actionCode: "BookLocal"
                            description: "##Getting the vaccine\nYou can get an RSV vaccination at your GP surgery.\nYour GP surgery may contact you about getting the RSV vaccine. This may be by letter, text, phone call, email or through the NHS App. You do not need to wait to be contacted before booking your vaccination."
                example_50000000004:
                  summary: RSV - Actionable due to membership of an Age Cohort including suggested action (future national booking)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "Actionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts: []
                        suitabilityRules: []
                        actions:
                          - actionType: "ButtonWithAuthLink"
                            actionCode: "AmendNBS"
                            description: "##You have an RSV vaccination appointment\nYou can view, change or cancel your appointment below."
                            urlLink: "http://www.nhs.uk/book-rsv"
                            urlLabel: "Manage your appointment"
                example_50000000005:
                  summary: RSV - Actionable due to membership of an Age Cohort including suggested actions (with future local booking)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "Actionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts: []
                        suitabilityRules: []
                        actions:
                          - actionType: "CardWithText"
                            actionCode: "ManageLocal"
                            description: "##You have an RSV vaccination appointment\nContact your healthcare provider to change or cancel your appointment."
                example_50000000006:
                  summary: RSV - Not Actionable despite to membership of an Age Cohort with reasoning of already vaccinated (cohorts hidden)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts: []
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "AlreadyVaccinated"
                            ruleText: "##You've had your RSV vaccination\nBased on our records, you recently had this vaccination. You do not need to do anything."
                        actions: []
                example_50000000007:
                  summary: RSV - Not Actionable despite to membership of an Age Cohort with reasoning of no available vaccinations (not available type 1)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are aged 75 to 79 years old."
                            cohortStatus: "NotActionable"
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "NotAvailable"
                            ruleText: "Vaccinations are not currently available"
                        actions: []
                example_50000000008:
                  summary: RSV - No RSV response as no active campaign (not available type 2)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions: []
                example_50000000009:
                  summary: RSV - Not Actionable despite to membership of an Age Cohort with reasoning of dose not yet due
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are aged 75 to 79 years old."
                            cohortStatus: "NotActionable"
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "NotYetDue"
                            ruleText: "Your next dose is not yet due."
                        actions: []
                example_50000000010:
                  summary: RSV - Not Actionable despite to membership of an Age Cohort with reasoning of dose not far enough apart
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are aged 75 to 79 years old."
                            cohortStatus: "NotActionable"
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "TooClose"
                            ruleText: "Your previous vaccination was less than 91 days ago."
                        actions: []
                example_50000000011:
                  summary: RSV - Not Actionable despite to membership of an Age Cohort with reasoning of vaccination given in other setting (e.g. care home)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are aged 75 to 79 years old."
                            cohortStatus: "NotActionable"
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "OtherSetting"
                            ruleText: "##Getting the vaccine\nOur record show you're living in a setting where care is provided.\nIf you think you should have the RSV vaccine, speak to a member of staff where you live."
                        actions: []
                example_50000000012:
                  summary: RSV - Not Actionable despite no cohort membership with reasoning of already vaccinated (type 1 includes unknown cohort)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts:
                          - cohortCode: "unknown_cohort_membership"
                            cohortText: "Our records do not say why you are eligible"
                            cohortStatus: "NotActionable"
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "AlreadyVaccinated"
                            ruleText: "##You've had your RSV vaccination\nBased on our records, you recently had this vaccination.You do not need to do anything."
                        actions: []
                example_50000000013:
                  summary: RSV - Not Actionable despite no cohort membership with reasoning of already vaccinated (type 2 includes no cohorts)
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotActionable"
                        statusText: "You should have the RSV vaccine"
                        eligibilityCohorts: []
                        suitabilityRules:
                          - ruleType: "S"
                            ruleCode: "AlreadyVaccinated"
                            ruleText: "##You've had your RSV vaccination\nBased on our records, you recently had this vaccination. You do not need to do anything."
                        actions: []
                example_50000000014:
                  summary: RSV - Not Eligible
                  value:
                    responseId: "1a233ba5-e1eb-4080-a086-2962f6fc3473"
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    processedSuggestions:
                      - condition: "RSV"
                        status: "NotEligible"
                        statusText: "We do not believe you should have this vaccine"
                        eligibilityCohorts:
                          - cohortCode: "rsv_age_rolling"
                            cohortText: "You are not aged 75 to 79 years old."
                            cohortStatus: "NotEligible"
                          - cohortCode: "rsv_age_catchup"
                            cohortText: "You did not turn 80 between 2nd September 2024 and 31st August 2025"
                            cohortStatus: "NotEligible"
                        suitabilityRules: []
                        actions:
                          - actionType: "InfoText"
                            actionCode: "HealtchareProInfo"
                            description: "##If you think you need this vaccine\nSpeak to your healthcare professional if you think you should be offered this vaccination."
        '400':
          description: Invalid input data.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-99999999-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-11T14:40:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: value
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: VALIDATION_ERROR
                                  display:
                                    type: string
                                    example: The given conditions were not in the expected format.
                        diagnostics:
                          type: string
                          example: 'FLU&COVID should be a single or comma separated list of condition strings with no other punctuation or special characters'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/conditions'
              examples:
                example_error_1:
                  summary: Invalid Input Data Error
                  value:
                    resourceType: "OperationOutcome"
                    id: rrt-2959959087381887325-c-geu2-24001-77777777-1
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                              code: VALIDATION_ERROR
                              display: "The given conditions were not in the expected format."
                        diagnostics: "FLU&COVID should be a single or comma separated list of condition strings with no other punctuation or special characters"
                        location:
                          - "parameters/conditions"
        '404':
          description: Person not found.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-82918062-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-14T11:35:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: processing
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: RESOURCE_NOT_FOUND
                                  display:
                                    type: string
                                    example: The given NHS number was not found in our datasets.  This could be because the number is incorrect or some other reason we cannot process that number.
                        diagnostics:
                          type: string
                          example: 'NHS Number 9000000404 was not recognised by the Eligibility Signposting API'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/patient'
              examples:
                example_error_1:
                  summary: Resource Not Found Error
                  value:
                    resourceType: "OperationOutcome"
                    id: rrt-2959959087381887325-c-geu2-24001-77777777-1
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    issue:
                      - severity: error
                        code: processing
                        details:
                          coding:
                            - system: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                              code: RESOURCE_NOT_FOUND
                              display: "The given NHS number was not found in our datasets.  This could be because the number is incorrect or some other reason we cannot process that number."
                        diagnostics: "NHS Number 9000000404 was not recognised by the Eligibility Signposting API"
                        location:
                          - "parameters/id"
        '422':
          description: 'Unrecognised input data. (Unprocessable Content)'
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-88888888-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-11T14:40:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: value
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: VALIDATION_ERROR
                                  display:
                                    type: string
                                    example: The supplied category was not recognised by the API.
                        diagnostics:
                          type: string
                          example: 'HEALTHCHECKS is not a category that is supported by the API'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/category'
              examples:
                example_error_1:
                  summary: Unrecognised Input Error
                  value:
                    resourceType: "OperationOutcome"
                    id: rrt-2959959087381887325-c-geu2-24001-77777777-1
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                              code: VALIDATION_ERROR
                              display: "The supplied category was not recognised by the API."
                        diagnostics: "HEALTHCHECKS is not a category that is supported by the API"
                        location:
                          - "parameters/category"
        '500':
          description: Internal server error.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-77777777-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-10T13:40:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: processing
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: SERVICE_ERROR
                                  display:
                                    type: string
                                    example: 'An unknown error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support quoting the id included in this message'
                        diagnostics:
                          type: string
                          example: 'No diagnostics available'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/category'
              examples:
                example_error_1:
                  summary: Internal Processing Error
                  value:
                    resourceType: "OperationOutcome"
                    id: rrt-2959959087381887325-c-geu2-24001-77777777-1
                    meta:
                      lastUpdated: "2025-02-12T16:11:22Z"
                    issue:
                      - severity: error
                        code: processing
                        details:
                          coding:
                            - system: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                              code: SERVICE_ERROR
                              display: "An unknown error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support quoting the id included in this message"
                        diagnostics: "No diagnostics available"
                        location:
                          - "parameters/category"
################################################################################
#                                 Components                                  #
################################################################################
components:
    securitySchemes:
      environment-specific-secured:
        $ref: "components/security/security.yaml"
x-nhsd-apim:
    access:
        $ref: "x-nhsd-apim/access.yaml"
    target:
        $ref: "x-nhsd-apim/target.yaml"
    ratelimiting:
        $ref: "x-nhsd-apim/ratelimit.yaml"
